/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 2 "outt4"
typedef unsigned long size_t;
#line 205
extern int printf(char const   * __restrict  __format  , ...) ;
#line 230
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
#line 706
extern  __attribute__((__nothrow__)) void *( __attribute__((__leaf__)) malloc)(size_t __size )  __attribute__((__malloc__)) ;
#line 713
extern  __attribute__((__nothrow__)) void ( __attribute__((__leaf__)) free)(void *__ptr ) ;
#line 821 "outt4"
int main(void) 
{ 
  int *p ;
  int *tmp ;
  int x ;
  int *f ;
  int *tmp___0 ;

  {
#line 822
  tmp = (int *)malloc(sizeof(int ));
#line 822
  p = tmp;
#line 824
  scanf((char const   * __restrict  )"%d", & x);
#line 825
  if (x > 10) {
#line 826
    free((void *)p);
#line 827
    printf((char const   * __restrict  )" x > 10, and pointer has deallocated \n");
#line 828
    return (0);
  } else {
#line 831
    printf((char const   * __restrict  )" x <= 10 \n");
#line 832
    return (0);
  }
#line 834
  printf((char const   * __restrict  )" x * 2 is %d \n", x * 2);
#line 835
  free((void *)p);
#line 836
  tmp___0 = (int *)malloc(sizeof(int ));
#line 836
  f = tmp___0;
#line 837
  free((void *)f);
#line 838
  return (0);
}
}
