/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 2 "outc"
typedef unsigned long size_t;
#line 207
extern int printf(char const   * __restrict  __format  , ...) ;
#line 232
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
#line 688
extern  __attribute__((__nothrow__)) void *malloc(size_t __size )  __attribute__((__malloc__)) ;
#line 695
extern  __attribute__((__nothrow__)) void free(void *__ptr ) ;
#line 805 "outc"
int main(int argc , char **argv ) 
{ 
  int *p ;
  int *tmp ;
  int *q ;
  int *tmp___0 ;
  int n ;
  int m ;

  {
#line 806
  tmp = (int *)malloc(sizeof(int ));
#line 806
  p = tmp;
#line 807
  tmp___0 = (int *)malloc(sizeof(int ));
#line 807
  q = tmp___0;
#line 808
  return (0);
#line 810
  scanf((char const   * __restrict  )"%d, %d", & n, & m);
#line 811
  if (n > 10) {
#line 812
    printf((char const   * __restrict  )" input num is greater than 10 \n");
#line 813
    if (p) {
#line 813
      free((void *)p);
#line 813
      p = (int *)((void *)0);
#line 813
      printf((char const   * __restrict  )" Pointer p has been deallocated \n");
    }
#line 814
    if (q) {
#line 814
      free((void *)q);
#line 814
      q = (int *)((void *)0);
#line 814
      printf((char const   * __restrict  )" Pointer q has been deallocated \n");
    }
#line 815
    return (0);
  }
#line 817
  if (p) {
#line 818
    *p = n;
  }
#line 819
  if (q) {
#line 820
    *q = m;
  }
#line 821
  printf((char const   * __restrict  )" n + m = %d\n", *p + *q);
#line 822
  if (p) {
#line 822
    free((void *)p);
#line 822
    p = (int *)((void *)0);
#line 822
    printf((char const   * __restrict  )" Pointer p has been deallocated \n");
  }
#line 823
  if (q) {
#line 823
    free((void *)q);
#line 823
    q = (int *)((void *)0);
#line 823
    printf((char const   * __restrict  )" Pointer q has been deallocated \n");
  }
#line 824
  return (0);
}
}
